id: P002947
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG01615
  title: ཟབ་ཆོས་ནི་གུ་ཆོས་དྲུག་གི་བརྒྱུད་འདེབས་ཉུང་འདུས་བདེ་ཆེན་འབེབས་པ
  author: ''
  volumes:
    cf9ae55df992438a907672d5b75cf4ef:
      image_group_id: I00KG02868
      title: ''
      volume_number: 1
      total_pages: 6
      base_file: v001.txt
